set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

set -g default-terminal "screen-256color"
set -g default-shell /bin/bash
set -g set-clipboard on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'ssh htop btop "~nvidia-smi" "claude->~/.tmux/scripts/claude-resume.sh"'
set -g @resurrect-hook-post-save-all '~/.tmux/scripts/claude-save-sessions.sh'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @continuum-boot 'on'

run '~/.tmux/plugins/tpm/tpm'
